# Generated by Django 5.2 on 2025-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('system-admin', 'System Admin'), ('unit-leader', 'Unit Leader'), ('logistics-officer', 'Logistics Officer')], max_length=32),
        ),
    ]
