# Generated by Django 5.2.1 on 2025-05-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notification_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('issued_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_item', to='api.issueditem')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_as_damaged_items', to=settings.AUTH_USER_MODEL)),
                ('repair_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_item_record', to='api.repairrequest')),
            ],
        ),
    ]
