# Generated by Django 5.2.1 on 2025-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_department_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='item',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='UNKWON', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
