# Generated by Django 5.2.1 on 2025-05-23 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_repairrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueditem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
