# Generated by Django 4.2.11 on 2025-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('in-stock', 'In Stock'), ('in-use', 'In Use'), ('under-repair', 'Under Repair'), ('damaged', 'Damaged')], default='in-stock', max_length=32),
        ),
    ]
