# Generated by Django 4.2.11 on 2025-05-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
