# Generated by Django 5.2.1 on 2025-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('deleted', 'Deleted')], default='available', max_length=32),
        ),
    ]
