# Generated by Django 5.2.1 on 2025-05-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('request_approved', 'Request Approved'), ('request_denied', 'Request Denied'), ('item_issued', 'Item Issued')], default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.request'),
        ),
    ]
