# Generated by Django 5.2.1 on 2025-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
