# Generated by Django 5.2.1 on 2025-05-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
