# Generated by Django 5.2.1 on 2025-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=32),
        ),
    ]
