# Generated by Django 5.2.1 on 2025-05-15 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_birth_date_user_rank_user_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to='api.item')),
            ],
        ),
    ]
