# Generated by Django 5.2.1 on 2025-05-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_item_serial_number_issueditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='issued_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_requests', to='api.issueditem'),
        ),
    ]
