# Generated by Django 5.2.1 on 2025-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_request_issued_item_repairrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
