# Generated by Django 5.2.1 on 2025-05-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueditem',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='issueditem',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
    ]
