# Generated by Django 4.2.11 on 2025-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_issueditem_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
