# Generated by Django 4.2.11 on 2025-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_issueditem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueditem',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, null=True, blank=True),
        ),
    ]
