[build]
  base = "project"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"
  port = 3000

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "npm run build"
  publish = "dist"
